<a href="https://colab.research.google.com/github/Yilder02/SyS_2025-1/blob/main/Python_Basic/Python_basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EJERCICIOS DE PYTHON BASICO
#1. VARIABLES


1.   Escribe un programa que muestre en pantalla el resultado de la siguiente operación aritmética:
$x(t) = \left( \frac{3 + 2}{2.5} \right)^2$



In [1]:
x=((3+2)/2.5)**2
print(x)

4.0




2.   Escribe un programa que le pida al usuario el número de horas trabajadas y la tarifa por hora. Luego, debe mostrar en pantalla el pago correspondiente.





In [2]:
h= input("¿cuantas horas ha trabajado?: ")
h=float(h)
t=input("¿Cuanto es la tarifa por hora?: ")
t=float(t)
s=h*t
print(s)


¿cuantas horas ha trabajado?: 8
¿Cuanto es la tarifa por hora?: 6000
48000.0


3. Escribe un programa que le pida al usuario su peso (en kilogramos) y su altura (en metros), calcule el índice de masa corporal (IMC), lo almacene en una variable y muestre en pantalla el mensaje "Su índice de masa corporal es imc", donde imc es el IMC calculado redondeado a dos cifras decimales.

In [3]:
p= input("Ingrese su peso (kg): ")
p=float(p)
a=input("Ingrese su altura (m): ")
a=float(a)
c=(p/((a)**2))
imc=round(c,2)
print("Su indice de masa corporal es: ",imc)

Ingrese su peso (kg): 58
Ingrese su altura (m): 1.67
Su indice de masa corporal es:  20.8


#2. CONDICIONALES
1. Para poder pagar un determinado impuesto es necesario ser mayor de 16 años y disponer de unos ingresos mensuales iguales o superiores a 1000€.
Escriba un programa que le pregunte al usuario su edad e ingresos mensuales, y muestre si el usuario tiene que pagar el impuesto o no.

In [4]:
ed=input("Ingrese su edad: " )
ed=int(ed)
ing=input("Escriba sus ingresos mensuales (€): ")
ing=float(ing)

if ed>16 and ing>=1000:
  print("El usuario debe pagar el impuesto")
else:
 print("El usuario NO debe pagar el impuesto")

Ingrese su edad: 24
Escriba sus ingresos mensuales (€): 45000
El usuario debe pagar el impuesto


2. La pizzería Bella Napoli ofrece pizzas vegetarianas y no vegetarianas a sus clientes. Los ingredientes para cada tipo de pizza son los siguientes:
Ingredientes vegetarianos: pimientos y tofu.
Ingredientes no vegetarianos: pepperoni, jamón y salmón.
Escriba un programa que le pregunte al usuario si quiere una pizza vegetariana o no y, en función de su respuesta, muestre un menú con los ingredientes disponibles para que elija.
Solo se puede elegir un ingrediente adicional además de la mozzarella y el tomate, que se incluyen en todas las pizzas.
Finalmente, el programa debe mostrar si la pizza elegida es vegetariana o no, junto con todos los ingredientes que contiene.

In [5]:
pi=input("¿Quiere una pizza vegetariana?.Escriba 0 si su respuesta es afirmativa ")
pi=int(pi)
if pi==0:
  print("Para su pizza vegetariana puede elegir pimiento o tofu")
else:
  print("Para su pizza puede elegir pepperoni, jamon o salmón")

print("Todas la pizzas llevan mozzarella y tomate, ademas del ingrediene adicional que desee")


if pi==0:
  ing=input("Ingrese el adicional que desee, recuerde que solo puede elegir pimiento o tofu")
  ing=str(ing)
  print("la pizza elegida es vegetariana y contiene mozzarella, tomate y ",ing)
else:
  ing=input("Ingrese el adicional que desee, recuerde que solo puede elegir pepperoni, jamon o salmon")
  ing=str(ing)
  print("Su pizza elegida no es vegetariana y contiene mozzarella,tomate y ",ing)


¿Quiere una pizza vegetariana?.Escriba 0 si su respuesta es afirmativa 0
Para su pizza vegetariana puede elegir pimiento o tofu
Todas la pizzas llevan mozzarella y tomate, ademas del ingrediene adicional que desee
Ingrese el adicional que desee, recuerde que solo puede elegir pimiento o tofutofu
la pizza elegida es vegetariana y contiene mozzarella, tomate y  tofu


#  3. Bucles
1. Escriba un código que le pida al usuario que ingrese un número entero cada vez,
y el proceso se repetirá con más números hasta que el usuario ingrese un cero.
Al final (cuando se ingresa el cero), muestra la cantidad de números ingresados.

In [6]:
num=input("Ingrese un numero entero: ")
num=int(num)
conNum=0
while num!=0:
  num=input("Ingrese un numero entero: ")
  num=int(num)
  conNum=conNum+1

print("La cantidad de numeros ingresados fue:",conNum)

Ingrese un numero entero: 4
Ingrese un numero entero: 5
Ingrese un numero entero: 2
Ingrese un numero entero: 4
Ingrese un numero entero: 3
Ingrese un numero entero: 1
Ingrese un numero entero: 0
La cantidad de numeros ingresados fue: 6


2. Use la función input() para pedirle al usuario que ingrese un número entero.
Solo si el número es par, se acumulará.
El programa debe finalizar si la suma de los números supera los 50 o si el usuario ingresa un máximo de 10 números.

In [10]:
sump=0
sum=0
i=0
while sum<50 and i<10:
  i=i+1
  ent=input("Ingrese un numero entero: ")
  ent=int(ent)
  sum=sum+ent
  #print(sum)
  if (ent % 2==0):
   sump=sump+ent

print("",sum,sump,i)

Ingrese un numero entero: 5
Ingrese un numero entero: 5
Ingrese un numero entero: 3
Ingrese un numero entero: 7
Ingrese un numero entero: 5
Ingrese un numero entero: 42
 67 42 6


#4. IntroNumpy
* ¿Qué es NumPy?:
NumPy (Numerical Python) es una biblioteca fundamental para computación científica en Python. Proporciona estructuras de datos eficientes y funciones para el manejo de arrays y matrices, además de herramientas matemáticas de alto nivel.

* ¿Qué es un array?:
Un array en NumPy es una estructura de datos similar a una lista, pero optimizada para operaciones matemáticas. Puede ser:

- Unidimensional (como un vector).

- Bidimensional (como una matriz).

In [30]:
# 2 EJEMPLOS
import numpy as np #Importar libreria

# Crear dos vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operaciones básicas
suma = a + b
resta = a - b
producto_punto = np.dot(a, b)

# Mostrar resultados
print("Vector a:", a)
print("Vector b:", b)
print("Suma:", suma)
print("Resta:", resta)
print("Producto punto:", producto_punto)


Vector a: [1 2 3]
Vector b: [4 5 6]
Suma: [5 7 9]
Resta: [-3 -3 -3]
Producto punto: 32


In [31]:
import numpy as np

# Crear dos matrices 2x2
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
#cada lista de números es tratada como una fila de las matrices A y B
# Suma de matrices
suma = A + B

# Producto matricial
producto = np.dot(A, B)

# Mostrar resultados
print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Suma de A y B:\n", suma)
print("Producto de A y B:\n", producto)


Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]
Suma de A y B:
 [[ 6  8]
 [10 12]]
Producto de A y B:
 [[19 22]
 [43 50]]


#5. FUNCIONES
1. Crea una función que tome la longitud de los lados del triángulo y devuelva el área del triángulo, redondeada a un decimal.
El módulo de matemáticas puede ayudarte a calcular la raíz cuadrada.

In [11]:
import math
def a_tri(s1,s2,s3):
  s=((s1+s2+s3)/2)
  a=math.sqrt(s*(s-s1)*(s-s2)*(s-s3))
  a=round(a,2)
  print ("El area del triangulo es de: ",a)

In [12]:
area= a_tri(10,12,3)


El area del triangulo es de:  12.18


2. Cree una función que pueda calcular el índice de masa corporal (IMC) de una persona.
La fórmula para calcular el IMC es la siguiente:
IMC = peso/(altura^2)

In [13]:
def IMC(p,a): #El usuario ingresa el peso en libras y la altura en pulgadas
   p=p*0.45
   a=a*0.025
   imc=p/(a**2)
   imc=round(imc,2)
   print ("Su IMC es de: ",imc)

In [14]:
p=float(input("Ingrese su peso en libras: "))
a=float(input("Ingrese su altura en pulgadas: "))
mc= IMC(p,a)

Ingrese su peso en libras: 35
Ingrese su altura en pulgadas: 123
Su IMC es de:  1.67


#6. ESTRCUTURAS
1. Escriba una función que tome una lista de números como entrada y devuelva la suma de todos los números impares de la lista.
Por ejemplo, si la entrada es [1, 2, 3, 4, 5, 6],
la función debería devolver 9 (que es la suma de 1, 3 y 5).

In [17]:
def sum(List):
  sumImpar=0
  for i in List:
    if i%2!=0:
      sumImpar+=i
  print("La suma de los numeros impares de la lista ingresada es de: ", sumImpar)

In [18]:
sum([1,2,3,4,5,6])


La suma de los numeros impares de la lista ingresada es de:  9


2. Escriba una función que tome una lista de palabras como entrada y devuelva un diccionario
que cuente el número de veces que aparece cada palabra en la lista. Por ejemplo,
si la entrada es ['manzana', 'plátano', 'manzana', 'cereza', 'cereza', 'cereza'],
la función debería devolver {'manzana': 2, 'plátano': 1, 'cereza': 3}.

In [19]:
def contar_palabras(lista_palabras):
    # Crear un diccionario vacío para almacenar las ocurrencias
    contador = {}

    # Recorrer la lista de palabras
    for palabra in lista_palabras:
        # Si la palabra ya está en el diccionario, aumentar su contador en 1
        if palabra in contador:
            contador[palabra] += 1
        # Si la palabra no está en el diccionario, agregarla con un contador de 1
        else:
            contador[palabra] = 1

    return contador

In [20]:
lista = ['manzana', 'plátano', 'manzana', 'cereza', 'cereza', 'cereza']
resultado = contar_palabras(lista)
print(resultado)

{'manzana': 2, 'plátano': 1, 'cereza': 3}


#7. CLASES
1. Crea una clase "Persona" que tenga atributos como nombre, edad, género y métodos para presentarse y saludar a otras personas.

In [21]:
class Persona:
  # Constructor de la clase
  def __init__(self, nombre, edad ,genero):
     self.nombre=nombre
     self.edad= edad
     self.genero=genero
  # Método para presentarse
  def presentarse(self):
    print( f"Hola, mi nombre es {self.nombre}, tengo {self.edad} años y soy {self.genero}.")
  # Método para saludar a otra persona
  def saludar(self,otra_persona):
     print( f"Hola {otra_persona.nombre}, soy {self.nombre}. ¡Mucho gusto!")

In [22]:
#Ejemplo:
persona1=Persona("Francisco",25,"hombre")
persona2=Persona("Alejandra",28,"mujer")

persona1.presentarse()
persona2.presentarse()

persona1.saludar(persona2)
persona2.saludar(persona1)

Hola, mi nombre es Francisco, tengo 25 años y soy hombre.
Hola, mi nombre es Alejandra, tengo 28 años y soy mujer.
Hola Alejandra, soy Francisco. ¡Mucho gusto!
Hola Francisco, soy Alejandra. ¡Mucho gusto!


2. Crea una clase "Coche" que tenga atributos como marca, modelo, año, kilometraje y métodos para arrancar, acelerar y frenar.

In [23]:
class Coche:
  def __init__(self,marca,modelo,año,kilometraje):
    self.marca=marca
    self.modelo=modelo
    self.año=año
    self.kilometraje=kilometraje
  #Metodo arrancar
  def arrancar(self):
   print(f"El coche {self.marca} ha arrancado")
  #Metodo acelerar
  def acelerar(self,velocidad):
   print(f"El coche a acelerado a una velocidad de {velocidad} km/h")
  #Metodo frenar
  def frenar(self):
   print(f"El coche {self.marca} ha frenado")

In [24]:
coche = Coche("Toyota", "Camry", 2022, 1000)

coche.arrancar()
coche.acelerar(60)
coche.frenar()

El coche Toyota ha arrancado
El coche a acelerado a una velocidad de 60 km/h
El coche Toyota ha frenado


3. Crea una clase "Rectángulo" que tenga atributos como longitud y ancho y métodos para calcular el área y el perímetro.

In [25]:
class rectangulo:
  def __init__(self,longitud,ancho):
    self.longitud=longitud
    self.ancho=ancho

  def area(self):
    a=self.longitud*self.ancho
    print(f"El area del rectangulo es {a}")
  def perimetro(self):
    p=2*(self.longitud+self.ancho)
    print(f"El perimetro del rectangulo es {p}")

rectangulo1=rectangulo(5,10)
rectangulo1.area()
rectangulo1.perimetro()


El area del rectangulo es 50
El perimetro del rectangulo es 30


4. Crea una clase "Banco" que tenga atributos como nombre, dirección y métodos para abrir una cuenta, depositar dinero, retirar dinero y revisar el saldo.

In [26]:
class Banco:
    def __init__(self, nombre, direccion):
        self.nombre = nombre
        self.direccion = direccion
        self.cuentas = {}  # Utilizamos un diccionario para almacenar las cuentas

    def abrir_cuenta(self, cliente, saldo_inicial=0):
        self.cuentas[cliente] = saldo_inicial
        print( f"Cuenta abierta para {cliente} en {self.nombre} con un saldo inicial de {saldo_inicial} dólares.")

    def depositar(self, cliente, cantidad):
        self.cuentas[cliente] += cantidad
        print (f"{cliente}, has depositado {cantidad} dólares. Saldo actual: {self.cuentas[cliente]} dólares.")

    def retirar(self, cliente, cantidad):
        if cantidad <= self.cuentas[cliente]:
            self.cuentas[cliente] -= cantidad
            print( f"{cliente}, has retirado {cantidad} dólares. Saldo actual: {self.cuentas[cliente]} dólares.")
        else:
            print (f"{cliente}, saldo insuficiente para realizar el retiro.")

    def revisar_saldo(self, cliente):
        print (f"Saldo actual de {cliente}: {self.cuentas[cliente]} dólares.")

#Ejemplo
mi_banco = Banco("Mi Banco", "Calle Principal, Ciudad")

mi_banco.abrir_cuenta("Cliente 1", 1000)
mi_banco.depositar("Cliente 1", 500)
mi_banco.retirar("Cliente 1", 1499)
mi_banco.revisar_saldo("Cliente 1")


Cuenta abierta para Cliente 1 en Mi Banco con un saldo inicial de 1000 dólares.
Cliente 1, has depositado 500 dólares. Saldo actual: 1500 dólares.
Cliente 1, has retirado 1499 dólares. Saldo actual: 1 dólares.
Saldo actual de Cliente 1: 1 dólares.


5. Crea una clase "Estudiante" que tenga atributos como nombre, edad, promedio y
métodos para estudiar, hacer tareas y presentar exámenes

In [27]:
class Estudiante:
    def __init__(self, nombre, edad, promedio):
        self.nombre = nombre
        self.edad = edad
        self.promedio = promedio

    def estudiar(self, horas_estudio):
        return f"{self.nombre} está estudiando durante {horas_estudio} horas."

    def hacer_tareas(self, horas_tareas):
        return f"{self.nombre} está haciendo tareas durante {horas_tareas} horas."

    def presentar_examen(self):
        if self.promedio >= 7.0:
            return f"{self.nombre} presentó el examen y aprobó con un promedio de {self.promedio}. ¡Felicidades!"
        else:
            return f"{self.nombre} presentó el examen pero no aprobó con un promedio de {self.promedio}. Deberá estudiar más."

# Ejemplo
estudiante1 = Estudiante("Juan", 18, 8.5)
estudiante2 = Estudiante("María", 20, 6.0)

print(estudiante1.estudiar(3))
print(estudiante2.hacer_tareas(2))

print(estudiante1.presentar_examen())
print(estudiante2.presentar_examen())


Juan está estudiando durante 3 horas.
María está haciendo tareas durante 2 horas.
Juan presentó el examen y aprobó con un promedio de 8.5. ¡Felicidades!
María presentó el examen pero no aprobó con un promedio de 6.0. Deberá estudiar más.


#8. HERENCIAS
1. Crea un sistema de manejo de figuras geométricas utilizando clases y herencia. Debes tener una clase base llamada "FiguraGeometrica" con un método abstracto llamado "calcular_area()". Luego, crea clases derivadas para diferentes tipos de figuras geométricas, como "Círculo", "Rectángulo" y "Triángulo". Cada clase derivada debe implementar el método "calcular_area()" de acuerdo con la fórmula correspondiente para el cálculo del área de esa figura.

In [28]:
import math

# Definición de la clase base FiguraGeometrica
class FiguraGeometrica:
    def calcular_area(self):
        pass

# Clase derivada para círculos
class Circulo(FiguraGeometrica):
    def __init__(self, radio):
        self.radio = radio

    def calcular_area(self):
        return round(math.pi * self.radio ** 2,2)

# Clase derivada para rectángulos
class Rectangulo(FiguraGeometrica):
    def __init__(self, base, altura):
        self.base = base
        self.altura = altura

    def calcular_area(self):
        return self.base * self.altura
# Clase derivada para triángulos
class Triangulo(FiguraGeometrica):
    def __init__(self, base, altura):
        self.base = base
        self.altura = altura

    def calcular_area(self):
        return 0.5 * self.base * self.altura

# Ejemplo de uso
circulo = Circulo(5)
print(f"Área del círculo: {circulo.calcular_area()}")

rectangulo = Rectangulo(4, 6)
print(f"Área del rectángulo: {rectangulo.calcular_area()}")

triangulo = Triangulo(3, 7)
print(f"Área del triángulo: {triangulo.calcular_area()}")


Área del círculo: 78.54
Área del rectángulo: 24
Área del triángulo: 10.5


2. Crea un sistema de reserva de vuelos utilizando clases y herencia. Debes tener una clase base llamada "Vuelo" con los siguientes atributos: número de vuelo, origen, destino, y capacidad máxima de pasajeros. Luego, crea una clase derivada llamada "VueloEconomico" que herede de la clase base y agregue un atributo adicional llamado "tarifa". Además, agrega métodos en ambas clases para mostrar la información del vuelo y realizar una reserva de asientos.
La clase base "Vuelo" debe tener un método para verificar si hay asientos disponibles y otro para realizar la reserva de un asiento. La clase derivada "VueloEconomico" puede tener métodos adicionales para calcular el precio total de la reserva de acuerdo con la tarifa y la cantidad de asientos reservados.

In [29]:
class Vuelo:
    def __init__(self, numero_vuelo, origen, destino, capacidad_maxima):
        self.numero_vuelo = numero_vuelo
        self.origen = origen
        self.destino = destino
        self.capacidad_maxima = capacidad_maxima
        self.asientos_disponibles = capacidad_maxima
        self.reservas = []

    def verificar_asientos_disponibles(self):
        return self.asientos_disponibles

    def realizar_reserva(self, num_asientos):
        if num_asientos <= self.asientos_disponibles:
            self.asientos_disponibles -= num_asientos
            self.reservas.append(num_asientos)
            print(f"Reserva exitosa para {num_asientos} pasajero(s).")
        else:
            print("Lo siento, no hay suficientes asientos disponibles.")
    def mostrar_informacion_vuelo(self):
        print(f"Vuelo {self.numero_vuelo}: {self.origen} -> {self.destino}")
        print(f"Capacidad máxima: {self.capacidad_maxima}")
        print(f"Asientos disponibles: {self.asientos_disponibles}")
class VueloEconomico(Vuelo):
    def __init__(self, numero_vuelo, origen, destino, capacidad_maxima, tarifa):
        super().__init__(numero_vuelo, origen, destino, capacidad_maxima)
        self.tarifa = tarifa

    def calcular_precio_total(self, num_asientos):
        return self.tarifa * num_asientos

# Ejemplo de uso
vuelo_regular = Vuelo("AA123", "Nueva York", "Los Ángeles", 150)
vuelo_regular.mostrar_informacion_vuelo()
vuelo_regular.realizar_reserva(3)
vuelo_regular.realizar_reserva(2)
vuelo_regular.mostrar_informacion_vuelo()

vuelo_economico = VueloEconomico("BB456", "Chicago", "Miami", 100, 200)
vuelo_economico.mostrar_informacion_vuelo()
vuelo_economico.realizar_reserva(4)
vuelo_economico.realizar_reserva(3)
vuelo_economico.mostrar_informacion_vuelo()
print(f"Precio total de la reserva: ${vuelo_economico.calcular_precio_total(4)}")


Vuelo AA123: Nueva York -> Los Ángeles
Capacidad máxima: 150
Asientos disponibles: 150
Reserva exitosa para 3 pasajero(s).
Reserva exitosa para 2 pasajero(s).
Vuelo AA123: Nueva York -> Los Ángeles
Capacidad máxima: 150
Asientos disponibles: 145
Vuelo BB456: Chicago -> Miami
Capacidad máxima: 100
Asientos disponibles: 100
Reserva exitosa para 4 pasajero(s).
Reserva exitosa para 3 pasajero(s).
Vuelo BB456: Chicago -> Miami
Capacidad máxima: 100
Asientos disponibles: 93
Precio total de la reserva: $800
